### ISSUE TITLE
options.distDir is absolute path

### ISSUE THREAD

**Issue by jam13** [elwin013/parcel-reporter-static-files-copy#1]
Using this with parcel 2.0.0-beta.1, the plugin is attempting to copy the static files to an invalid path.

This seems to be because `options.distDir` is an absolute path which for a file `foo` results in:

`/project/root//project/root/dist/foo`

**Comment by elwin013** [comment]
Hello @jam13,
could you share your config, npm/node version and OS?

**Comment by elwin013** [comment]
@jam13 Please check v1.1.0, available now on npmjs.

**Comment by Matt-McConway** [comment]
Hi :) On windows there are some further path issues where nothing gets copied - I think it's just due to the hardcoded forward slashes in the filepaths so should be easy to resolve with the path library. Let me know if you need any more info

**Comment by elwin013** [comment]
Hello @Matt-McConway! You're right ;-) v1.1.1 should be fixed - published to npmjs. If you could test it and tell if everything is OK - that would be great!

**Comment by Matt-McConway** [comment]
@elwin013 Thanks for the prompt fix! Seems to work for my usecase now (not overriding the static or dist path)

**Comment by jam13** [comment]
> @jam13 Please check v1.1.0, available now on npmjs.

@elwin013 Thanks for the update. That looks like it will work for me, will test later today.

Is there a reason why you dropped using `options.distDir` entirely? Having to define the a non standard dist dir twice (in package.json and parcel CLI) seems awkward. I had a go at getting a working patch last week and was trying something along the same lines but with:

```
let distPath = options.distDir || path.join(options.projectRoot, "dist");
```

**Comment by elwin013** [comment]
@jam13 Reason is very very simple - it was not working (`distDir` was always empty) in Parcel version I've downloaded from npmjs ;-) But I've checked and it is working with `2.0.0-beta.1`, so I've bring it back with 1.2.0 version - just published to npmjs.

**Comment by elwin013** [comment]
Looks like everything is working now as expected. Closing this issue ;-)
