### ISSUE TITLE
Cannot connect to Parcel development server when parcel-reporter-static-files-copy is enabled

### ISSUE THREAD

**Issue by openjck** [elwin013/parcel-reporter-static-files-copy#14]
### Steps to reproduce

1. Clone [this repo](https://github.com/openjck/bug-demo-parcel-reporter-static-files-copy-14)
2. Run `npm install`
3. Run `npm run dev`
4. Open http://localhost:1234. the default server URL, in your browser

### Actual result

The browser reports that it cannot connect to http://localhost:1234.

### Expected result

The Parcel development server runs as expected and index.html is served.

### Other notes

Follow these steps to get the Parcel development server to run again:

1. Remove line 3 (`"reporters": ...`) from *.parcelrc*
2. Run `npm run dev`

**Comment by openjck** [comment]
Oh my. Is this happening because the `...` is literal in the *.parcelrc* configuration file? Should the line 3 look literally like this?

```
  "reporters":  ["...", "parcel-reporter-static-files-copy"]
```

That's... odd, but if that's the cause, it's certainly not your fault.

**Comment by openjck** [comment]
Yep, that is [special syntax](https://v2.parceljs.org/configuration/plugin-configuration/#pipelines). I have to say, that is really weird, but it's certainly not your fault. Sorry to be a nusiance.

**Comment by tschaub** [comment]
Bit by the same.  Thanks for figuring out the mystery.

**Comment by elwin013** [comment]
Hello @openjck and @tschaub! Yes, this is Parcel special syntax to include all default plugins. I'm glad that you're figured it out!
