### ISSUE TITLE
Maybe "@parcel/plugin" should be a peer dependencies ?

### ISSUE THREAD

**Issue by vcarel** [elwin013/parcel-reporter-static-files-copy#17]
The plugin depends on `@parcel/plugin`. But I presume it should be a peer dependency. Shouldn't it?

BTW: thanks for the plugin, it's simple but amazing ❤️

**Comment by elwin013** [comment]
Hey @vcarel! Thanks!

That should be peer dependency in the end. I've changed it in 1.3.1 (already published). :-)

**Comment by elwin013** [comment]
I've reverted change in 1.3.3 to follow the way it is in official plugins. This also (probably!) make plugin visible in https://parceljs.org/plugin-browser/
