### ISSUE TITLE
Fails to resolve paths on windows

### ISSUE THREAD

**Issue by jorgeka** [elwin013/parcel-reporter-static-files-copy#19]
Use the resolved destination path and relative path, rather than a string-replacement, which fails on windows environments, because `filepath.replace(copyFrom, copyTo)` does not play nice with '\\'-characters.
Fixed in #18

**Comment by elwin013** [comment]
Fixed with 1.3.2 - published on npmjs.com

Thank you @jorgeka for the fix!
