### ISSUE TITLE
Parcel start fails (silently) to start server

### ISSUE THREAD

**Issue by basher** [elwin013/parcel-reporter-static-files-copy#2]
I've just tried your plugin with `"parcel": "^2.0.0-nightly.400"`.
It works as described when running the `build` command, and would therefore be ideal for our CI pipeline.

However, when running the `start` command, which executes `"parcel src/ts/index.ts --port 1234 --no-cache --target app"`, it fails silently.

- The parcel server at `localhost:1234` doesn't start at all.
- I need the Parcel server to start as it serves all the CSS/JS for our local .NET development environment.

When I **remove your plugin**, this is my terminal output, showing server starting OK:

![image](https://user-images.githubusercontent.com/452809/108972246-014fe400-767b-11eb-93ee-fcb4e7b21ccb.png)

I notice in your code that the static file copying is performed when `(event.type === "buildSuccess")`.

Is there a way to prevent your plugin "firing" at all when running `start` command?

**Comment by pReya** [comment]
Same here. After installing this plugin, parcel server is not starting anymore. No errors given.

**Comment by basher** [comment]
Thanks @elwin013 

I got your plugin to work with `start` command eventually...

To cut a long story short, I re-installed all my NPM modules from scratch after first deleting my `npm-shrinkwrap.json`.

And I installed `parcel@nightly` rather than the latest specific version as I had a breakages with PostCSS and Babel.

I now need to fix Storybook, but that's another matter altogether!

**Comment by basher** [comment]
Update... I just realised that `build` does not complete.

I have a `postbuild` task that doesn't fire now... more investigating needed!

**Comment by basher** [comment]
I've written a simple Node script to do the copying in our repo, which provides all the functionality we need, rather than spending any more time trying to wrangle Parcel 2 (nightly) issues.

```JavaScript
// 'copy-static-assets'.
const fs = require('fs-extra');
const path = require('path');
const directoryPathInput = path.join(__dirname, '../../static');
const directoryPathOutput = path.join(__dirname, '../../dist');
if (process.env.NODE_ENV === 'PROD ') {
    fs.copy(directoryPathInput, directoryPathOutput, function (err) {
        if (err) {
            return console.log(err);
        }
    });
}
```

And here's how it's run via NPM scripts in `package.json`:

```json
"scripts": {
    "copy-static-assets": "node ./src/scripts/copy-static-assets",
    "build": "parcel build src/ts/index.ts --dist-dir dist && npm run copy-static-assets",
}
```

Once Parcel 2 is released as a stable version, I might revisit all this.

**Comment by elwin013** [comment]
@basher Closing this issue in that case ;-) When you revisit it later - please create new one. Thank you :-)
