### ISSUE TITLE
Support copying single files instead of directories

### ISSUE THREAD

**Issue by PSanetra** [elwin013/parcel-reporter-static-files-copy#20]
I have a use case where my static file that I want to copy, is located in the same directory as the target index.html file. As I don't want to copy the index.html file, which is processed by parcel, it would be nice to copy only that single file or alternatively ignore the index.html in the target directory.

**Comment by elwin013** [comment]
This is now available with `1.4.0` version of the plugin. For details please check [this example](https://github.com/elwin013/parcel-reporter-static-files-copy/tree/master/examples/singleFile).
