### ISSUE TITLE
Multiple sources to destinations

### ISSUE THREAD

**Issue by damianobarbati** [elwin013/parcel-reporter-static-files-copy#4]
Is there a solution to support multiple source-destination like v1?

```json
"staticFiles": {
        "staticPath": [
            {
                "staticPath": "assets/robots.txt",
                "staticOutDir": ""
            },
            {
                "staticPath": "assets",
                "staticOutDir": "assets"
            }
        ],
        "watcherGlob": "**"
    },
```

**Comment by elwin013** [comment]
Helo @damianobarbati!

At this moment there is no feature like this. Maybe in future someone (me or someone else) will add it.

**Comment by juancarrey** [comment]
This one supports multiple sources https://github.com/jvidalv/parcel-reporter-static-file-copier

**Comment by folknor** [comment]
This would be excellent because in all the static apps I deploy there's loads of assets I don't want exposed in `/www` - so my `/dist` folder always looks like `/dist/www`, `/dist/config`, etc, and in the config folder I copy in PHP dependencies and such and also files with SMTP passwords for example, but POST entrypoint handling scripts and other static assets need to go in `/dist/www`.

**Comment by Drecu** [comment]
I think my PR should solve this problem, had the same issue where i have multiple different files under different paths and needed to export them. See my pr https://github.com/elwin013/parcel-reporter-static-files-copy/pull/13

**Comment by web1100manager** [comment]
@elwin013 if @Drecu 's solution works can we please get that merged? This would be a huge help. Thank you!

**Comment by elwin013** [comment]
Feature is added with 1.5.0 version of plugin. Plugin now allows to things:
1. multiple configurations (just set `staticFiles` to array and put as many configs as you wish),
2. env variable matching (all variables must match), example config:
```json
// package.json
  {
  ...
  "staticFiles": [
    {
      "staticPath": "production.txt",
      "env": {
        "NODE_ENV": "production"
      }
    },
    {
      "staticPath": "development.txt",
      "env": {
        "NODE_ENV": "development"
      }
    }
  ]
```
