### ISSUE TITLE
Error is thrown if designated static folder doesn't contain a folder

### ISSUE THREAD

**Issue by owenDods** [elwin013/parcel-reporter-static-files-copy#6]
Hi all,

Appreciate your work on this - really useful plugin!

But I ran into an issue when using it for a project where the designated `static` folder didn't contain a folder itself i.e. just files.

I was able to replicate this issue by deleting the "magic" folder from within the [customOutInDistFolder from within your examples](https://github.com/elwin013/parcel-reporter-static-files-copy/tree/master/examples/customOutInDistFolder/static).

By taking a brief look at your code, it seems that if there isn't a `directory` present, then when `copy` is called within `copyDir` `mkdirSync` is never called resulting in an `ENOENT` error - since there is no target directory to transfer into.

I may be way off the mark with this if this is the intended behaviour: if so, it might be worth mentioning the required folder structure in the README to avoid other users encountering this error.

Thanks again!

**Comment by elwin013** [comment]
hey @owenDods!

For sure this is (unexpected) bug, will fix it. And your brief looking is accurate folder is not created, so copying files failed. :-) 

Thanks for finding this!

**Comment by owenDods** [comment]
No worries! Glad I could help 😄

**Comment by elwin013** [comment]
@owenDods it is fixed now with version 1.2.2. :-)
