### ISSUE TITLE
--dist-dir getting ignored

### ISSUE THREAD

**Issue by GauBen** [elwin013/parcel-reporter-static-files-copy#9]
Hello,

I have noticed that the `--dist-dir` command argument given to parcel is always ignored.

After searching the cause of this issue, I have noticed that `options.distDir` is always `undefined`. 

https://github.com/elwin013/parcel-reporter-static-files-copy/blob/0ce37b57a3dba58a2cae9719ec9e348c773b153b/index.js#L13-L16

Indeed, `options.distDir` does not appear on the interface [PluginOptions](https://v2.parceljs.org/plugin-system/api/#PluginOptions).

This forces to define `staticFiles.distDir` in package.json, even when it should be the same as the command argument `--dist-dir`.

I'm not sure whether this bug is related to parcel-reporter-static-files-copy or parcel, but I can't find a way to get `distDir` from the options object.

Have a nice day,
Gautier

**Comment by elwin013** [comment]
Hey @GauBen,
thank you for raising this. :-) 

There are some changes between beta.1 and beta.2 versions. I've created issue in parcel repo regarding this (and linked to this issue). Will update this one when get more details.

**Comment by elwin013** [comment]
@GauBen, should work now as expected with 1.3.0 version - just published to NPM repository. :-)

**Comment by GauBen** [comment]
Thanks for the quick fix!
